# Generated by Django 5.2.10 on 2026-04-13 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0002_movie_duration_minutes_alter_cinema_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='location_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
