# Generated by Django 5.2.10 on 2026-04-13 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0003_cinema_location_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
